### ISSUE TITLE
sd_pipeline Invalid source - Windows 10 / Linux Mint - Shared Drive

### ISSUE THREAD

**Issue by FuzzyCactusLogic** [Bismuth-Consultancy-BV/MLOPs#134] opened 2024-01-05 10:59 UTC
Error | Invalid source /obj/geo1/sd_pipeline1/sd_solver1/solver.(Error: Python error: Traceback (most recent call last):File "<stdin>", line 52, in <module>File "E:\Github/MLOPS/MLOPs/scripts/python\sdpipeline\image_solve.py", line 183, in runnoise_pred = unet(File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_implreturn forward_call(*args, **kwargs)File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\unet_2d_condition.py", line 956, in forwardsample, res_samples = downsample_block(File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_implreturn forward_call(*args, **kwargs)File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\unet_2d_blocks.py", line 1086, in forwardhidden_states = attn(File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_implreturn forward_call(*args, **kwargs)File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\transformer_2d.py", line 315, in forwardhidden_states = block(File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_implreturn forward_call(*args, **kwargs)File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\attention.py", line 218, in forwardattn_output = self.attn2(File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_implreturn forward_call(*args, **kwargs)File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\attention_processor.py", line 420, in forwardreturn self.processor(File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\attention_processor.py", line 1006, in __call__batch_size, sequence_length, _ = (ValueError: too many values to unpack (expected 3)).
-- | --

</body></html>Error 
Invalid source [/obj/geo1/sd_pipeline1/sd_solver1/solver](node:/obj/geo1/sd_pipeline1/sd_solver1/solver).
(Error: Python error: Traceback (most recent call last):
File "<stdin>", line 52, in <module>
File "E:\Github/MLOPS/MLOPs/scripts/python\sdpipeline\image_solve.py", line 183, in run
noise_pred = unet(
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\unet_2d_condition.py", line 956, in forward
sample, res_samples = downsample_block(
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\unet_2d_blocks.py", line 1086, in forward
hidden_states = attn(
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\transformer_2d.py", line 315, in forward
hidden_states = block(
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\attention.py", line 218, in forward
attn_output = self.attn2(
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\attention_processor.py", line 420, in forward
return self.processor(
File "E:\Github\MLOPS\MLOPs\data\dependencies\python\diffusers\models\attention_processor.py", line 1006, in __call__
batch_size, sequence_length, _ = (
ValueError: too many values to unpack (expected 3)
).

Backward and Forward Slashes in file path, possibly due to my E(Projects): Drive being accessible from Windows and Linux OS?

File "E:\Github/MLOPS/MLOPs/scripts/python\sdpipeline\image_solve.py"

**Comment by gzimmermann123** [comment] 2024-01-06 14:50
seems a duplicate of https://github.com/Bismuth-Consultancy-BV/MLOPs/issues/133

and I have the same issue

**Comment by Ambrosiussen** [comment] 2024-02-11 13:16
Latest commit on the repo fixed this

**Closed by Ambrosiussen** 2024-02-11 13:16 UTC
